export const bgMainColor = '#424242';
export const colorLightGrey = '#e6e6e6';
export const colorDarkGrey = '#424646';

// Default theme
const arvatoblue = '#0068A9';
const darkGrey = '#2D2C2C';
const mediumGrey = '#C0C0C0';
const grey = '#D5D5D5';
const lightgrey = '#F4F4F4';
const white = '#FFFFFF';
const black = '#000000';
const accentBlue = '#4A6A7D';
const activeColor = '#DFEAF0';

// Darkmode
const darkmodeDarkGrey = '#1D2126';
const darkmodeBlack = '#1D2126';

// High contrast
const highContrastWaterblue = '#42BBD9';
const highContrastAppleGreen = '#B0C800';
const highContrastActiveColorYellow = '#ffef00';

// Common
const durationLabelBackground = 'rgba(0, 0, 0, 0.6)';

const stateColors = {
  success: {
    main: '#5EE2A0',
  },
  warning: {
    main: '#FFDD00',
    dark: '#F57C00',
  },
  error: {
    main: '#E03434',
    light: '#E57373',
  },
  default: {
    main: mediumGrey,
  },
  info: {
    main: '#2196F3',
  },
};

export const lightMode = {
  focusBlue: '#c5deec',
  filterToggleBtnBackground: activeColor,
  cunstomRangeBackground: lightgrey,
  customRangeBetweenDates: activeColor,
  customRangeBetweenCells: lightgrey,
  filterRangeBackground: lightgrey,
  white,
  arvatoBlue: arvatoblue,
  darkBlue: '#002649',
  lightBlue: activeColor,
  errorColor: '#D05D5D',
  arrowColor: white,
  relatedTableRow: white,
  innerWrapper: lightgrey,
  arrowBackground: white,
  playerTimeline: darkGrey,
  darkGreyAccent: darkGrey,
  inactiveGrey: mediumGrey,
  contentBorder: 'none',
  workflowTabs: mediumGrey,
  selectedTab: darkGrey,
  onHoverTextColor: '#002749',
  inactiveTextColor: lightgrey,
  filterBorderColor: mediumGrey,
  inactive: white,
  mediumGrey,
  lightGrey: grey,
  btnBackgroundColor: lightgrey,
  backgroundLightGrey: lightgrey,
  playerSortingColor: lightgrey,
  medadataAccordionBg: lightgrey,
  backgroundColor: lightgrey,
  btnHoverColor: arvatoblue,
  medadataAccordionBorder: '#CCD4DB',
  searchSuggestionsDropdown: 'transparent',
  containerBackground: lightgrey,
  fontColorPrimary: black,
  filterPanel: mediumGrey,
  tablehover: activeColor,
  tablehoverWithLowOpacity: 'rgba(223, 234, 240, 0.5)',
  tablehoverWithHightOpacity: 'rgba(223, 234, 240, 0.8)',
  elementBackgroundColor: white,
  segmentInputColor: lightgrey,
  modalBackground: lightgrey,
  adornment: 'transparent',
  tableHeadingColor: mediumGrey,
  iconColor: arvatoblue,
  iconColors: arvatoblue,
  iconAsText: darkGrey,
  tableHead: grey,
  btnColor: white,
  btnGroupColor: grey,
  selectedElement: activeColor,
  selectedElementDark: darkGrey,
  borderColor: '#EAEAEA',
  generalBorderColor: grey,
  boxShadow: '#bbb9b9',
  tableheadborder: '#D8D8D8',
  playerButtonsBG: '#D8D8D8',
  playerBorderColor: '#CCD4DB',
  playerBufferingBG: 'rgba(0, 104, 169, 0.5)',
  loaderOverlayColor: 'rgba(255,255,255,0.8)',
  durationLabelBackground,
  globalWhite: white,
  globalSvgColor: white,
  globalBlack: black,
  transparent: 'transparent',
  globalTextColor: black,
  globalMediumGrey: mediumGrey,
  svgColor: black,
  disabledBtnHover: activeColor,
  disabledSvgcolor: mediumGrey,
  globaldarkGrey: darkGrey,
  globalAccentBlue: accentBlue,
  globalAccentGreen: highContrastAppleGreen,
  paginationCurrent: grey,
  breadcrumbsShowMore: black,
  disabledSubtitles: grey,
  darkGrey: darkmodeDarkGrey,
  ...stateColors,
};

export const darkMode = {
  focusBlue: '#02243a',
  filterToggleBtnBackground: ' #394855',
  cunstomRangeBackground: darkmodeDarkGrey,
  customRangeBetweenDates: 'rgba(0, 104, 169, 0.8)',
  customRangeBetweenCells: '#21313F',
  filterRangeBackground: '#394855',
  white,
  arvatoBlue: arvatoblue,
  playerTimeline: darkGrey,
  errorColor: '#D05D5D',
  darkGreyAccent: darkmodeDarkGrey,
  inactiveGrey: '#707070',
  inactive: white,
  mediumGrey: '#424141',
  lightGrey: '#292828',
  arrowColor: darkmodeDarkGrey,
  arrowBackground: darkmodeDarkGrey,
  onHoverTextColor: white,
  filterBorderColor: '#21313F',
  backgroundLightGrey: '#101010',
  playerSortingColor: '#101010',
  btnBackgroundColor: darkmodeBlack,
  relatedTableRow: darkmodeDarkGrey,
  innerWrapper: '#101010',
  btnHoverColor: arvatoblue,
  medadataAccordionBg: black,
  medadataAccordionBorder: darkmodeDarkGrey,
  containerBackground: '#101010',
  tableheadborder: '#292828',
  searchSuggestionsDropdown: 'transparent',
  fontColorPrimary: white,
  filterPanel: '#21313F',
  tablehover: '#003251',
  tablehoverWithLowOpacity: 'rgba(0, 50, 81, 0.5)',
  tablehoverWithHightOpacity: 'rgba(0, 50, 81, 0.8)',
  workflowTabs: '#21313F',
  selectedTab: '#003251',
  uploadlist: darkmodeDarkGrey,
  elementBackgroundColor: darkmodeDarkGrey,
  segmentInputColor: '#101010',
  modalBackground: '#556573',
  adornment: arvatoblue,
  tableHeadingColor: '#21313F',
  iconColor: white,
  iconColors: white,
  backgroundColor: lightgrey,
  tableHead: '#292828',
  iconAsText: white,
  btnColor: white,
  btnGroupColor: '#394855',
  selectedElement: '#003251',
  selectedElementDark: '#003251',
  borderColor: black,
  generalBorderColor: '#292828',
  boxShadow: black,
  playerButtonsBG: '#394855',
  playerBorderColor: '#CCD4DB',
  playerBufferingBG: '#394855',
  loaderOverlayColor: 'rgba(0,0,0,0.8)',
  durationLabelBackground,
  globalWhite: black,
  globalBlack: white,
  transparent: 'transparent',
  globalSvgColor: white,
  globalMediumGrey: '#424141',
  disabledSvgcolor: '#707070',
  svgColor: white,
  inactiveTextColor: lightgrey,
  disabledBtnHover: '#003251',
  globaldarkGrey: darkGrey,
  contentBorder: 'none',
  globalAccentBlue: accentBlue,
  globalTextColor: white,
  globalAccentGreen: highContrastAppleGreen,
  paginationCurrent: '#292828',
  breadcrumbsShowMore: white,
  disabledSubtitles: lightgrey,
  darkGrey: darkmodeDarkGrey,

  ...stateColors,
};

export const highContrastMode = {
  focusBlue: '#42bbd9',
  filterToggleBtnBackground: black,
  cunstomRangeBackground: black,
  customRangeBetweenDates: 'rgba(66, 187, 217, 0.8)',
  filterRangeBackground: black,
  white,
  arvatoBlue: highContrastWaterblue,
  errorColor: '#D05D5D',
  darkGreyAccent: black,
  inactiveGrey: white,
  inactive: black,
  playerTimeline: highContrastWaterblue,
  workflowTabs: black,
  selectedTab: darkGrey,
  filterBorderColor: white,
  mediumGrey: black,
  lightGrey: black,
  arrowColor: white,
  arrowBackground: black,
  backgroundLightGrey: black,
  playerSortingColor: '#101010',
  uploadlist: black,
  innerWrapper: black,
  relatedTableRow: black,
  btnBackgroundColor: black,
  medadataAccordionBg: black,
  medadataAccordionBorder: white,
  containerBackground: '#101010',
  tableheadborder: white,
  searchSuggestionsDropdown: white,
  backgroundColor: black,
  btnHoverColor: highContrastActiveColorYellow,
  fontColorPrimary: white,
  filterPanel: black,
  tablehover: highContrastActiveColorYellow,
  tablehoverWithLowOpacity: 'rgba(255, 239, 0, 0.5)',
  tablehoverWithHightOpacity: 'rgba(255, 239, 0, 0.8)',
  onHoverTextColor: black,
  elementBackgroundColor: black,
  segmentInputColor: black,
  modalBackground: '#556573',
  adornment: highContrastWaterblue,
  tableHeadingColor: black,
  iconColor: white,
  iconColors: black,
  disabledSvgcolor: black,
  iconAsText: white,
  btnColor: black,
  btnGroupColor: black,
  selectedElement: highContrastActiveColorYellow,
  selectedElementDark: '#003251',
  borderColor: white,
  generalBorderColor: white,
  boxShadow: black,
  playerButtonsBG: black,
  playerBorderColor: '#CCD4DB',
  playerBufferingBG: '#394855',
  loaderOverlayColor: 'rgba(0,0,0,0.8)',
  durationLabelBackground,
  globalWhite: black,
  globalBlack: white,
  transparent: white,
  globaldarkGrey: black,
  globalSvgColor: black,
  globalMediumGrey: white,
  globalDark: black,
  svgColor: white,
  disabledBtnHover: highContrastActiveColorYellow,
  tablehead: black,
  globalAccentBlue: highContrastAppleGreen,
  inactiveTextColor: lightgrey,
  contentBorder: '1px solid #ffffff',
  globalTextColor: white,
  globalAccentGreen: highContrastAppleGreen,
  paginationCurrent: white,
  breadcrumbsShowMore: black,
  disabledSubtitles: lightgrey,
  darkGrey: darkmodeDarkGrey,
  ...stateColors,
};
